### ISSUE TITLE
arp-listener throw exception when traffice sniffer

### ISSUE THREAD

**Issue by cxueqin** [bencevans/node-arp-listener#4]
Hi:
      I used arp-listern to monitor ARP broadcast packet. I found the nodejs main prcess exit, the console output was:
```
/Users/robbie/workspace/guiyuan/netfrog/netfrog/node_modules/arp-listener/index.js:22
    packet.sender_ha = bufferToHardwareAddress(new Buffer(packet.sender_ha.addr))                                                                          
TypeError: Cannot read property 'addr' of undefined
    at PcapSession.<anonymous> (/Users/robbie/workspace/guiyuan/netfrog/netfrog/node_modules/arp-listener/index.js:22:75)
    at emitOne (events.js:115:13)
    at PcapSession.emit (events.js:210:7)
    at PcapSession.on_packet_ready (/Users/robbie/workspace/guiyuan/netfrog/netfrog/node_modules/pcap/pcap.js:99:10)
    at packet_ready (/Users/robbie/workspace/guiyuan/netfrog/netfrog/node_modules/pcap/pcap.js:44:14)
    at SocketWatcher.pcap_read_callback [as callback] (/Users/robbie/workspace/guiyuan/netfrog/netfrog/node_modules/pcap/pcap.js:64:45)
```
    I used arp-listener 1.0.0. I think arp-listener is a very useful module. I don't know what cause the problem. So I submit the problem here. Any idea is appreciated.

**Comment by bencevans** [comment]
This would suggest `packet.sender_ha` doesn't exist on the parsed packet. Editing your local copy of this module, please could you print out the packet variable at https://github.com/bencevans/node-arp-listener/blob/bef2fa91037446ed27104e13b543d0dcd523b739/index.js#L21 and send what you get?

**Comment by cxueqin** [comment]
Thanks for reply. Now I can't  re-produce the problem. I will try your suggest and print out packet variable. I think maybe it's the some bug of pcap module for the code 
`
function listen (iface, arpPacketListener) {
  var pcapSession = pcap.createSession(iface, 'arp')

  pcapSession.on('packet', function (rawPacket) {
    var packet = pcap.decode.packet(rawPacket).payload.payload

    packet.sender_ha = bufferToHardwareAddress(new Buffer(packet.sender_ha.addr))
    packet.target_ha = bufferToHardwareAddress(new Buffer(packet.target_ha.addr))

    arpPacketListener(packet)
  })
}
`
Most of the decoding work is done by pcap module.  

If the problem happen again, I will feedback.
